export interface Product {
  id: string;
  nameHe: string;
  nameEn: string;
  descriptionHe: string;
  descriptionEn: string;
  price: number;
  category: "rings" | "necklaces" | "bracelets" | "earrings";
  image: string;
  images: string[];
  material: string;
  isNew?: boolean;
  isBestseller?: boolean;
}

// Ring angle pool — mix for 360° simulation until real photos arrive
const R = [
  "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=90",
  "https://images.unsplash.com/photo-1583292650898-7d22cd27ca6f?w=800&q=90",
  "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=800&q=90",
  "https://images.unsplash.com/photo-1589674781759-c21c37956a44?w=800&q=90",
  "https://images.unsplash.com/photo-1635767798638-3665a0a107fc?w=800&q=90",
  "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?w=800&q=90",
];

const N = [
  "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=90",
  "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=800&q=90",
  "https://images.unsplash.com/photo-1576022162879-bd9f5c8e5c6b?w=800&q=90",
  "https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=800&q=90",
  "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=90",
  "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=90",
];

const B = [
  "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=90",
  "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=90",
  "https://images.unsplash.com/photo-1540585268978-2d62e9fcf8e0?w=800&q=90",
  "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=90",
  "https://images.unsplash.com/photo-1576022162879-bd9f5c8e5c6b?w=800&q=90",
];

const E = [
  "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=90",
  "https://images.unsplash.com/photo-1573408301185-9519f94816b4?w=800&q=90",
  "https://images.unsplash.com/photo-1549049950-48d5887197a4?w=800&q=90",
  "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=90",
  "https://images.unsplash.com/photo-1573408301185-9519f94816b4?w=800&q=90",
];

export const products: Product[] = [
  /* ──────────────── RINGS ──────────────── */
  {
    id: "p1",
    nameHe: "טבעת ערוגה",
    nameEn: "Garden Ring",
    descriptionHe: "טבעת זהב 18 קראט עם יהלום טבעי מעוצבת בהשראת טבע הצפון",
    descriptionEn: "18k gold ring with natural diamond, inspired by Nordic nature",
    price: 2800,
    category: "rings",
    image: R[0],
    images: [R[0], R[1], R[2], R[3], R[4]],
    material: "זהב 18K | 18K Gold",
    isNew: true,
  },
  {
    id: "p5",
    nameHe: "טבעת ברד",
    nameEn: "Hail Ring",
    descriptionHe: "טבעת כסף מעוצבת עם פנינה לבנה טבעית",
    descriptionEn: "Silver ring with natural white pearl",
    price: 980,
    category: "rings",
    image: R[2],
    images: [R[2], R[5], R[0], R[3], R[1]],
    material: "כסף 925 | 925 Silver",
  },
  {
    id: "p7",
    nameHe: "טבעת נצח",
    nameEn: "Eternity Ring",
    descriptionHe: "טבעת זהב אנטיק עם שורת יהלומים בקו ישר — סמל לאהבה נצחית",
    descriptionEn: "Antique gold eternity band with a row of diamonds",
    price: 4200,
    category: "rings",
    image: R[1],
    images: [R[1], R[0], R[4], R[2], R[5]],
    material: "זהב 18K | 18K Gold",
    isBestseller: true,
  },
  {
    id: "p8",
    nameHe: "טבעת ניצן",
    nameEn: "Bud Ring",
    descriptionHe: "טבעת זהב לבן עם אבן רובי אדומה — עיצוב עדין ונועז כאחד",
    descriptionEn: "White gold ring with a vivid ruby stone",
    price: 3500,
    category: "rings",
    image: R[3],
    images: [R[3], R[1], R[5], R[0], R[4]],
    material: "זהב לבן 18K | 18K White Gold",
    isNew: true,
  },
  {
    id: "p9",
    nameHe: "טבעת ענן",
    nameEn: "Cloud Ring",
    descriptionHe: "טבעת זהב צהוב עם קו מינימליסטי — מתאימה לכל אצבע",
    descriptionEn: "Yellow gold minimalist band, stackable and versatile",
    price: 1200,
    category: "rings",
    image: R[4],
    images: [R[4], R[2], R[0], R[5], R[3]],
    material: "זהב 14K | 14K Gold",
  },
  {
    id: "p10",
    nameHe: "טבעת כוכב",
    nameEn: "Star Ring",
    descriptionHe: "טבעת כסף בעיצוב כוכב, נוצצת ועדינה — לימי יום-יום ולאירועים",
    descriptionEn: "Silver star-shaped ring, delicate and luminous",
    price: 750,
    category: "rings",
    image: R[5],
    images: [R[5], R[3], R[1], R[4], R[2]],
    material: "כסף 925 | 925 Silver",
    isNew: true,
  },

  /* ──────────────── NECKLACES ──────────────── */
  {
    id: "p2",
    nameHe: "שרשרת שחר",
    nameEn: "Dawn Necklace",
    descriptionHe: "שרשרת זהב עדינה עם תליון אבן ירח, אלגנטית לכל אירוע",
    descriptionEn: "Delicate gold necklace with moonstone pendant",
    price: 1950,
    category: "necklaces",
    image: N[0],
    images: [N[0], N[1], N[2], N[3], N[4]],
    material: "זהב 14K | 14K Gold",
    isBestseller: true,
  },
  {
    id: "p6",
    nameHe: "שרשרת לב שקט",
    nameEn: "Quiet Heart Necklace",
    descriptionHe: "שרשרת זהב עם תליון לב עדין, מתנה מושלמת",
    descriptionEn: "Gold heart pendant necklace, the perfect gift",
    price: 1650,
    category: "necklaces",
    image: N[2],
    images: [N[2], N[0], N[5], N[1], N[3]],
    material: "זהב 14K | 14K Gold",
    isBestseller: true,
  },
  {
    id: "p11",
    nameHe: "שרשרת לונה",
    nameEn: "Luna Necklace",
    descriptionHe: "שרשרת כסף ארוכה עם תליון ירח — מיסטית ועדינה",
    descriptionEn: "Long silver necklace with crescent moon pendant",
    price: 890,
    category: "necklaces",
    image: N[3],
    images: [N[3], N[1], N[4], N[2], N[0]],
    material: "כסף 925 | 925 Silver",
    isNew: true,
  },
  {
    id: "p12",
    nameHe: "שרשרת ים",
    nameEn: "Sea Necklace",
    descriptionHe: "שרשרת זהב צהוב בשרשרת ונציאנית עם אבן כחולה",
    descriptionEn: "Yellow gold Venetian chain with blue topaz",
    price: 2100,
    category: "necklaces",
    image: N[4],
    images: [N[4], N[0], N[2], N[5], N[1]],
    material: "זהב 14K | 14K Gold",
  },
  {
    id: "p13",
    nameHe: "שרשרת אינפיניטי",
    nameEn: "Infinity Necklace",
    descriptionHe: "שרשרת כסף 925 בצורת אינפיניטי — סמל לנצח ולאהבה ללא גבולות",
    descriptionEn: "Sterling silver infinity symbol necklace",
    price: 720,
    category: "necklaces",
    image: N[5],
    images: [N[5], N[3], N[0], N[4], N[2]],
    material: "כסף 925 | 925 Silver",
  },
  {
    id: "p14",
    nameHe: "שרשרת ורד",
    nameEn: "Rose Necklace",
    descriptionHe: "שרשרת זהב ורד 14K עם יהלום קטן — אלגנטיות יומיומית",
    descriptionEn: "14K rose gold necklace with small diamond solitaire",
    price: 2400,
    category: "necklaces",
    image: N[1],
    images: [N[1], N[4], N[0], N[3], N[5]],
    material: "זהב ורד 14K | 14K Rose Gold",
    isBestseller: true,
  },

  /* ──────────────── BRACELETS ──────────────── */
  {
    id: "p3",
    nameHe: "צמיד שקט",
    nameEn: "Silence Bracelet",
    descriptionHe: "צמיד זהב לבן עם אבני ספיר כחולות עדינות",
    descriptionEn: "White gold bracelet with delicate blue sapphires",
    price: 3200,
    category: "bracelets",
    image: B[0],
    images: [B[0], B[1], B[2], B[3], B[4]],
    material: "זהב לבן 18K | 18K White Gold",
  },
  {
    id: "p15",
    nameHe: "צמיד זהב כבד",
    nameEn: "Bold Gold Bracelet",
    descriptionHe: "צמיד שרשרת זהב כבד ומרשים — נועד להיראות",
    descriptionEn: "Heavy gold chain bracelet — bold and statement-making",
    price: 4800,
    category: "bracelets",
    image: B[1],
    images: [B[1], B[0], B[3], B[2], B[4]],
    material: "זהב 18K | 18K Gold",
    isBestseller: true,
  },
  {
    id: "p16",
    nameHe: "צמיד טנגל",
    nameEn: "Tangle Bracelet",
    descriptionHe: "צמיד זהב עם חוליות שזורות — מודרני וקל לנשיאה",
    descriptionEn: "Interlocking gold link bracelet — modern and wearable",
    price: 2200,
    category: "bracelets",
    image: B[2],
    images: [B[2], B[4], B[1], B[3], B[0]],
    material: "זהב 14K | 14K Gold",
    isNew: true,
  },
  {
    id: "p17",
    nameHe: "צמיד חמסה",
    nameEn: "Hamsa Bracelet",
    descriptionHe: "צמיד כסף עם תליוני חמסה — מקסים, מגן ועדין",
    descriptionEn: "Silver bracelet with delicate hamsa charms",
    price: 680,
    category: "bracelets",
    image: B[3],
    images: [B[3], B[0], B[2], B[4], B[1]],
    material: "כסף 925 | 925 Silver",
  },
  {
    id: "p18",
    nameHe: "צמיד אינפיניטי",
    nameEn: "Infinity Bracelet",
    descriptionHe: "צמיד זהב ורד עם סמל אינפיניטי — מתנת אהבה מושלמת",
    descriptionEn: "Rose gold infinity bracelet — the perfect love gift",
    price: 1580,
    category: "bracelets",
    image: B[4],
    images: [B[4], B[2], B[0], B[1], B[3]],
    material: "זהב ורד 14K | 14K Rose Gold",
    isNew: true,
  },

  /* ──────────────── EARRINGS ──────────────── */
  {
    id: "p4",
    nameHe: "עגילי ציפור",
    nameEn: "Bird Earrings",
    descriptionHe: "עגילי זהב בצורת נוצה, קלים ומינימליסטיים",
    descriptionEn: "Feather-shaped gold earrings, light and minimal",
    price: 1400,
    category: "earrings",
    image: E[0],
    images: [E[0], E[1], E[2], E[3], E[4]],
    material: "זהב 14K | 14K Gold",
    isNew: true,
  },
  {
    id: "p19",
    nameHe: "עגילי פנינה",
    nameEn: "Pearl Earrings",
    descriptionHe: "עגילי פנינה לבנה טבעית בתלייה — קלאסי ונצחי",
    descriptionEn: "Natural white pearl drop earrings — classic and timeless",
    price: 1100,
    category: "earrings",
    image: E[1],
    images: [E[1], E[2], E[0], E[4], E[3]],
    material: "פנינה טבעית | Natural Pearl",
    isBestseller: true,
  },
  {
    id: "p20",
    nameHe: "עגילי יהלום",
    nameEn: "Diamond Studs",
    descriptionHe: "עגילי פאף יהלום קלאסיים בזהב לבן — חיוניים לכל ארון תכשיטים",
    descriptionEn: "Classic diamond stud earrings in white gold — a jewelry essential",
    price: 3800,
    category: "earrings",
    image: E[2],
    images: [E[2], E[0], E[3], E[1], E[4]],
    material: "זהב לבן 18K | 18K White Gold",
    isBestseller: true,
  },
  {
    id: "p21",
    nameHe: "עגילי חישוק זהב",
    nameEn: "Gold Hoop Earrings",
    descriptionHe: "עגילי חישוק זהב קלאסיים בקוטר בינוני — לכל יום ולכל ערב",
    descriptionEn: "Classic medium gold hoop earrings for any occasion",
    price: 920,
    category: "earrings",
    image: E[3],
    images: [E[3], E[1], E[4], E[0], E[2]],
    material: "זהב 14K | 14K Gold",
    isNew: true,
  },
  {
    id: "p22",
    nameHe: "עגילי טיפה",
    nameEn: "Teardrop Earrings",
    descriptionHe: "עגילי זהב בצורת טיפה עם אבן אמתיסט — רומנטיים ומרשימים",
    descriptionEn: "Gold teardrop earrings with amethyst — romantic and striking",
    price: 1750,
    category: "earrings",
    image: E[4],
    images: [E[4], E[2], E[0], E[3], E[1]],
    material: "זהב 14K | 14K Gold",
  },
  {
    id: "p23",
    nameHe: "עגילי כוכב",
    nameEn: "Star Stud Earrings",
    descriptionHe: "עגילי כסף בצורת כוכב עם זירקון לבן — קלים ומנצנצים",
    descriptionEn: "Silver star earrings with white zirconia — light and sparkly",
    price: 580,
    category: "earrings",
    image: E[0],
    images: [E[0], E[2], E[4], E[1], E[3]],
    material: "כסף 925 | 925 Silver",
    isNew: true,
  },
  {
    id: "p24",
    nameHe: "עגילי קשת",
    nameEn: "Arc Earrings",
    descriptionHe: "עגילי זהב ורד בקשת מינימליסטית — טרנד 2025 שכאן להישאר",
    descriptionEn: "Rose gold arc earrings — the 2025 minimal trend",
    price: 1300,
    category: "earrings",
    image: E[1],
    images: [E[1], E[3], E[0], E[4], E[2]],
    material: "זהב ורד 14K | 14K Rose Gold",
  },
];

export const categories = [
  { id: "all",       labelHe: "הכל",      labelEn: "All" },
  { id: "rings",     labelHe: "טבעות",    labelEn: "Rings" },
  { id: "necklaces", labelHe: "שרשראות",  labelEn: "Necklaces" },
  { id: "bracelets", labelHe: "צמידים",   labelEn: "Bracelets" },
  { id: "earrings",  labelHe: "עגילים",   labelEn: "Earrings" },
];
